import { useMemo, useState } from 'react'
import {
  BarChart3,
  CalendarDays,
  Download,
  FileSpreadsheet,
  FileText,
  Loader2,
} from 'lucide-react'
import {
  Bar,
  BarChart,
  CartesianGrid,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts'
import { PageHeader } from '@/components/layout/PageHeader'
import { useMobileNav } from '@/components/layout/useMobileNav'
import { Card, SectionTitle } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { Badge } from '@/components/ui/Badge'
import { Label, Select } from '@/components/ui/Field'
import { DataTable, type Column } from '@/components/ui/DataTable'
import { EmptyState, TableSkeleton } from '@/components/ui/States'
import { useToast } from '@/components/ui/Toast'
import { axisTick, chart, tooltipStyle } from '@/components/charts/chartTheme'
import {
  columnLabels,
  formatCell,
  reportColumns,
  reportPeriods,
  reportTypes,
  type ReportPeriod,
  type ReportRow,
  type ReportType,
  type SavedReport,
} from '@/data/reports'
import { download, messageOf } from '@/lib/api'
import { useApi } from '@/lib/useApi'

interface ReportPayload {
  period: ReportPeriod
  type: ReportType
  columns: (keyof ReportRow)[]
  rows: (ReportRow & { key: string })[]
  totals: Record<string, number> | null
}

interface HistoryPayload {
  reports: { id: string; name: string; generated: string; generatedBy: string; format: string }[]
}

const formatIcon = { PDF: FileText, CSV: FileSpreadsheet, XLSX: FileSpreadsheet }

/** Module 6 FE-7 — daily, weekly and monthly operational reports. */
export function ReportsPage() {
  const { toggle } = useMobileNav()
  const { push } = useToast()

  const [type, setType] = useState<ReportType>('Reservations')
  const [period, setPeriod] = useState<ReportPeriod>('Daily')
  const [generating, setGenerating] = useState(false)
  const [generated, setGenerated] = useState(true)
  const [range, setRange] = useState('Last 7 periods')

  // The range picker maps onto how many aggregated periods the server returns.
  const limit = range === 'Last 7 periods' ? 7 : range === 'Last 30 periods' ? 30 : 400
  // Rows are aggregated server-side from the stored daily series, so weekly and
  // monthly figures always reconcile with the daily ones.
  const reportQuery = useApi<ReportPayload>('/reports', { period, type, limit })
  const historyQuery = useApi<HistoryPayload>('/reports/history')

  const rows = reportQuery.data?.rows ?? []
  const metrics = reportColumns[type]

  const saved: SavedReport[] = (historyQuery.data?.reports ?? []).map((r) => ({
    id: r.id.slice(-6).toUpperCase(),
    name: r.name,
    type,
    period,
    generated: new Date(r.generated).toLocaleString('en-GB', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    }),
    generatedBy: r.generatedBy,
    format: (r.format as SavedReport['format']) ?? 'CSV',
  }))

  const totals = useMemo(() => {
    const primary = metrics[0]
    const values = rows.map((r) => r[primary] as number)
    const sum = values.reduce((a, b) => a + b, 0)
    return {
      primary,
      sum,
      avg: values.length ? sum / values.length : 0,
      peak: rows.length
        ? rows.reduce(
            (best, r) => ((r[primary] as number) > (best[primary] as number) ? r : best),
            rows[0],
          )
        : null,
    }
  }, [rows, metrics])

  const generate = async () => {
    setGenerating(true)
    setGenerated(false)
    reportQuery.refresh()
    await new Promise((r) => setTimeout(r, 400))
    setGenerating(false)
    setGenerated(true)
    push({ tone: 'success', title: 'Report generated', detail: `${period} ${type.toLowerCase()} report` })
  }

  /**
   * CSV is generated by the server so the file matches the table exactly.
   * PDF uses the browser's own print-to-PDF against the print stylesheet —
   * there is no server-side PDF renderer in this build.
   */
  const exportAs = async (format: SavedReport['format']) => {
    if (format === 'PDF') {
      window.print()
      return
    }

    try {
      await download(
        '/reports/export',
        { period, type },
        `smartdine-${type.toLowerCase().replace(/\s+/g, '-')}-${period.toLowerCase()}.csv`,
      )
      push({ tone: 'success', title: 'Exported as CSV', detail: 'Check your downloads folder.' })
      historyQuery.refresh()
    } catch (err) {
      push({ tone: 'error', title: 'Export failed', detail: messageOf(err) })
    }
  }

  const columns: Column<ReportRow>[] = [
    { key: 'period', header: 'Period', className: 'font-semibold text-ink', render: (r) => r.period },
    ...metrics.map<Column<ReportRow>>((m) => ({
      key: m,
      header: columnLabels[m],
      align: 'center',
      render: (r) => formatCell(m, r[m] as number),
    })),
  ]

  const savedColumns: Column<SavedReport>[] = [
    { key: 'id', header: 'Report ID', render: (r) => r.id },
    { key: 'name', header: 'Report Name', className: 'font-semibold text-ink', render: (r) => r.name },
    { key: 'type', header: 'Type', render: (r) => <Badge tone="neutral">{r.type}</Badge> },
    { key: 'period', header: 'Period', align: 'center', render: (r) => r.period },
    { key: 'generated', header: 'Generated', render: (r) => r.generated },
    { key: 'by', header: 'Generated By', render: (r) => r.generatedBy },
    {
      key: 'format',
      header: 'Format',
      align: 'center',
      render: (r) => {
        const Icon = formatIcon[r.format]
        return (
          <span className="inline-flex items-center gap-1.5 text-ink-soft">
            <Icon className="size-[14px] text-brand-600" />
            {r.format}
          </span>
        )
      },
    },
    {
      key: 'action',
      header: 'Action',
      align: 'center',
      className: 'w-[170px]',
      render: () => (
        <div className="flex items-center justify-center gap-1.5">
          <Button
            size="xs"
            variant="outline"
            leftIcon={<Download className="size-[11px]" />}
            onClick={() => exportAs('CSV')}
          >
            Download again
          </Button>
        </div>
      ),
    },
  ]

  return (
    <>
      <PageHeader
        title="Reports"
        underline
        onToggleNav={toggle}
        action={
          <Button
            leftIcon={
              generating ? (
                <Loader2 className="size-[15px] animate-spin" />
              ) : (
                <BarChart3 className="size-[15px]" />
              )
            }
            disabled={generating}
            onClick={generate}
          >
            {generating ? 'Generating…' : 'Generate Report'}
          </Button>
        }
      />

      <div className="grid gap-4 px-[var(--page-pad-x)] py-[var(--page-pad-y)]">
        {/* Report builder */}
        <Card className="p-4" data-print-hide>
          <SectionTitle icon={<FileText className="size-[16px]" strokeWidth={2.3} />}>
            1. Build a Report
          </SectionTitle>
          <p className="mt-1 text-[11.5px] text-ink-muted">
            Reservations, revenue, food wastage, staff requirement and sales forecasting — daily,
            weekly or monthly.
          </p>

          <div className="mt-3.5 grid gap-3 sm:grid-cols-2 lg:grid-cols-[repeat(3,minmax(0,1fr))_auto] lg:items-end">
            <div>
              <Label htmlFor="rp-type">Report Type</Label>
              <Select
                id="rp-type"
                value={type}
                onChange={(e) => {
                  setType(e.target.value as ReportType)
                  setGenerated(true)
                }}
                options={reportTypes.map((t) => ({ value: t, label: t }))}
              />
            </div>
            <div>
              <Label htmlFor="rp-period">Period</Label>
              <Select
                id="rp-period"
                icon={<CalendarDays />}
                value={period}
                onChange={(e) => {
                  setPeriod(e.target.value as ReportPeriod)
                  setGenerated(true)
                }}
                options={reportPeriods.map((p) => ({ value: p, label: p }))}
              />
            </div>
            <div>
              <Label htmlFor="rp-range">Date Range</Label>
              <Select
                id="rp-range"
                value={range}
                onChange={(e) => {
                  setRange(e.target.value)
                  setGenerated(true)
                }}
                options={[
                  { value: 'Last 7 periods', label: 'Last 7 periods' },
                  { value: 'Last 30 periods', label: 'Last 30 periods' },
                  { value: 'Year to date', label: 'All available' },
                ]}
              />
            </div>
            <div className="flex gap-2">
              <Button
                variant="outline"
                leftIcon={<FileText className="size-[14px]" />}
                onClick={() => exportAs('PDF')}
                disabled={!generated}
              >
                PDF
              </Button>
              <Button
                variant="outline"
                leftIcon={<FileSpreadsheet className="size-[14px]" />}
                onClick={() => exportAs('CSV')}
                disabled={!generated}
              >
                CSV
              </Button>
            </div>
          </div>
        </Card>

        {/* Result */}
        <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_300px]">
          <Card className="min-w-0 overflow-hidden">
            <div className="flex flex-wrap items-center justify-between gap-2 border-b border-line px-4 py-3.5">
              <h2 className="text-[14px] font-bold text-ink">
                {period} {type} Report
              </h2>
              <p className="text-[11.5px] text-ink-muted">{rows.length} periods</p>
            </div>

            {generating ? (
              <TableSkeleton rows={6} cols={metrics.length + 1} />
            ) : rows.length === 0 ? (
              <EmptyState
                title="No data for this period"
                detail="Try a different report type or widen the date range."
              />
            ) : (
              <DataTable columns={columns} rows={rows} rowKey={(r) => r.period} minWidth={760} />
            )}
          </Card>

          <div className="grid h-fit gap-4">
            <Card className="p-4">
              <SectionTitle icon={<BarChart3 className="size-[16px]" strokeWidth={2.3} />}>
                Summary
              </SectionTitle>

              <dl className="mt-3 grid gap-2.5">
                <SummaryRow label={`Total ${columnLabels[totals.primary].toLowerCase()}`} value={formatCell(totals.primary, totals.sum)} />
                <SummaryRow label="Average per period" value={formatCell(totals.primary, Math.round(totals.avg))} />
                <SummaryRow label="Best period" value={totals.peak?.period ?? '—'} />
              </dl>

              <div className="mt-4 h-[150px]">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={rows} margin={{ top: 4, right: 4, bottom: 0, left: -22 }} barCategoryGap="34%">
                    <CartesianGrid stroke={chart.grid} vertical={false} />
                    <XAxis
                      dataKey="period"
                      tick={{ ...axisTick, fontSize: 8 }}
                      tickLine={false}
                      axisLine={{ stroke: chart.grid }}
                      tickFormatter={(v: string) => v.split(/[,·(]/)[0].trim().slice(0, 6)}
                    />
                    <YAxis tick={axisTick} tickLine={false} axisLine={false} width={40} />
                    <Tooltip {...tooltipStyle} cursor={{ fill: '#F6F4F2' }} />
                    <Bar
                      dataKey={totals.primary}
                      name={columnLabels[totals.primary]}
                      fill={chart.maroon}
                      radius={[2, 2, 0, 0]}
                    />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </Card>
          </div>
        </div>

        {/* Report library */}
        <Card className="overflow-hidden" data-print-hide>
          <div className="flex flex-wrap items-center justify-between gap-2 px-4 py-3.5">
            <SectionTitle icon={<FileSpreadsheet className="size-[16px]" strokeWidth={2.3} />}>
              2. Saved Reports
            </SectionTitle>
            <p className="text-[11.5px] text-ink-muted">
              {saved.length} export{saved.length === 1 ? '' : 's'} recorded in the audit trail
            </p>
          </div>

          {saved.length === 0 ? (
            <EmptyState
              icon={<FileText className="size-6" strokeWidth={1.7} />}
              title="No saved reports yet"
              detail="Generate a report above and export it to add it to the library."
            />
          ) : (
            <DataTable columns={savedColumns} rows={saved} rowKey={(r) => r.id} minWidth={980} />
          )}
        </Card>
      </div>

    </>
  )
}

function SummaryRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between gap-3 rounded-[9px] bg-[#FBF9F7] px-3 py-2.5">
      <dt className="text-[11.5px] text-ink-soft">{label}</dt>
      <dd className="text-[12.5px] font-bold text-ink">{value}</dd>
    </div>
  )
}
